
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: odoo-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:17
    container_name: odoo-17
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8069:8069"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ODOO_MASTER_PASSWORD=${ODOO_MASTER_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./custom_addons:/mnt/extra-addons
      - ./odoo/data:/var/lib/odoo
      - ./odoo/logs:/var/log/odoo
